#!/bin/bash
#PBS -r n
#PBS -m bea
#PBS -M daniel.tanner@tyndall.ie
#PBS -N BulkXXX
#PBS -q default
#PBS -l nodes=1:ppn=1
#PBS -l walltime=60:00:00.00



export PATH=$PATH:/gpfs/sfihome/daniel.tanner/LammpsCopy/lammps-30Oct14/src
export PATH=$PATH:/local/pgi147/linux86-64/2014/mpi/mpich/bin
export PATH=$PATH:/local/pgi147/linux86-64/2014/mpi/mpich/lib


#--------------------------------
NP=`wc -l ${PBS_NODEFILE}`
#-------------------------------
#  MPI run command:
#------------------------------

echo cpus: $NP
echo nodes: `cat ${PBS_NODEFILE}`
echo $PATH

cd ${PBS_O_WORKDIR}

../../../SupercellSRC/compile_execute_QW_InGaN 64 64 40 XXX 25 1 40 false 0 0
/sfihome/daniel.tanner/GulpToLammpsSRC/SRC_Ver_Jun2016/mai supercell_corr2.dat /sfihome/daniel.tanner/GulpToLammpsSRC/SRC_Ver_Jun2016/Pots > mai.txt


