#!/bin/bash
#PBS -r n
#PBS -m bea
#PBS -M daniel.tanner@tyndall.ie
#PBS -N test
#PBS -q default
#PBS -l nodes=1:ppn=4
##PBS -l walltime=800:05:00.00

export PATH=$PATH:/sfihome/daniel.tanner/lammps-16Feb16/src
export PATH=$PATH:/sfihome/local/pgi1510/linux86-64/2015/mpi/mpich/bin
export PATH=$PATH:/sfihome/local/pgi1510/linux86-64/2015/mpi/mpich/lib

#--------------------------------
NP=`wc -l ${PBS_NODEFILE}`
#-------------------------------
#  MPI run command:
#------------------------------

echo cpus: $NP
echo nodes: `cat ${PBS_NODEFILE}`
echo $PATH

cd ${PBS_O_WORKDIR}

/sfihome/local/pgi1510/linux86-64/2015/mpi/mpich/bin/mpirun -np 4 -machinefile ${PBS_NODEFILE} lmp_pgi < in.pppm > NewLammps.txt


#../Posish log.lammps Gulp.gin dump.lammps > PositionsOutput.txt


