#!/bin/bash
#PBS -r n
#PBS -m bea
#PBS -M daniel.tanner@tyndall.ie
#PBS -N PreProc_25_XXX
#PBS -q default
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00.00



export PATH=$PATH:/gpfs/sfihome/daniel.tanner/LammpsCopy/lammps-30Oct14/src
export PATH=$PATH:/local/pgi147/linux86-64/2014/mpi/mpich/bin
export PATH=$PATH:/local/pgi147/linux86-64/2014/mpi/mpich/lib


#--------------------------------
NP=`wc -l ${PBS_NODEFILE}`
#-------------------------------
#  MPI run command:
#------------------------------

echo cpus: $NP
echo nodes: `cat ${PBS_NODEFILE}`
echo $PATH

cd ${PBS_O_WORKDIR}

../../../SupercellSRC/compile_execute_QW_InGaN XXX 25 21 32 19 20
../../../SRC_Ver_Jan2018/mai supercell_corr2.dat ../../../SRC_Ver_Jan2018/Pots > mai.txt



