#!/bin/bash
#PBS -r n
#PBS -m bea
#PBS -M stefan.schulz@tyndall.ie
#PBS -N PreProc_10_2
#PBS -q default
#PBS -l nodes=1:ppn=1
#PBS -l walltime=6:00:00.00



export PATH=$PATH:/gpfs/sfihome/stefan.schulz/LAMPS_Compiled_Daniel/LammpsCopy/lammps-30Oct14/src
export PATH=$PATH:/local/pgi147/linux86-64/2014/mpi/mpich/bin
export PATH=$PATH:/local/pgi147/linux86-64/2014/mpi/mpich/lib


#--------------------------------
NP=`wc -l ${PBS_NODEFILE}`
#-------------------------------
#  MPI run command:
#------------------------------

echo cpus: $NP
echo nodes: `cat ${PBS_NODEFILE}`
echo $PATH

cd ${PBS_O_WORKDIR}

~/Josh_scripts/SupercellSRC/compile_execute_QW_InGaN 32 32 40 2 05 21 32 true 19 20
/sfihome/stefan.schulz/Daniel_Scripts_4_Conversion/GulpToLammpsSRC/SRC_Ver_Jun2016/mai supercell_corr2.dat /sfihome/stefan.schulz/Daniel_Scripts_4_Conversion/GulpToLammpsSRC/SRC_Ver_Jun2016/Pots > mai.txt

#for i in `seq 31 60`
#do
#   cd Config${i}; 
#   ../Posish log.lammps Gulp.gin dump.lammps > PositionsOutput.txt
#   cd ..
#done





